name       : libvips
version    : 8.13.0
release    : 36
source     :
    - https://github.com/libvips/libvips/releases/download/v8.13.0/vips-8.13.0.tar.gz : b7e1d50dcf571165beecd36adece6eca6701c2a9e131c675143d8b9418dbdd81
homepage   : https://www.libvips.org/
license    : LGPL-2.1-or-later
component  : multimedia.library
summary    : A fast image processing library with low memory needs
description: |
    libvips is a demand-driven, horizontally threaded image processing library. Compared to similar libraries, libvips runs quickly and uses little memory.
builddeps  :
    - pkgconfig(ImageMagick)
    - pkgconfig(OpenEXR)
    - pkgconfig(cfitsio)
    - pkgconfig(fftw3)
    - pkgconfig(gtk-doc)
    - pkgconfig(lcms2)
    - pkgconfig(libexif)
    - pkgconfig(libheif)
    - pkgconfig(libgsf-1)
    - pkgconfig(libpng)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(libturbojpeg)
    - pkgconfig(libtiff-4)
    - pkgconfig(libwebp)
    - pkgconfig(orc-0.4)
    - pkgconfig(pangoft2)
    - pkgconfig(poppler-glib)
    - giflib-devel
setup      : |
    %meson_configure -Dgtk_doc=true
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
