name       : libvips
version    : 8.10.6
release    : 25
source     :
    - https://github.com/libvips/libvips/releases/download/v8.10.6/vips-8.10.6.tar.gz : 2468088d958e0e2de1be2991ff8940bf45664a826c0dad12342e1804e2805a6e
license    : LGPL-2.1-or-later
component  : multimedia.library
summary    : A fast image processing library with low memory needs
description: |
    libvips is a demand-driven, horizontally threaded image processing library. Compared to similar libraries, libvips runs quickly and uses little memory.
builddeps  :
    - pkgconfig(ImageMagick)
    - pkgconfig(OpenEXR)
    - pkgconfig(cfitsio)
    - pkgconfig(fftw3)
    - pkgconfig(gtk-doc)
    - pkgconfig(lcms2)
    - pkgconfig(libexif)
    - pkgconfig(libgsf-1)
    - pkgconfig(libpng)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(libturbojpeg)
    - pkgconfig(libtiff-4)
    - pkgconfig(libwebp)
    - pkgconfig(orc-0.4)
    - pkgconfig(pangoft2)
    - pkgconfig(poppler-glib)
    - pkgconfig(pygobject-3.0)
    - giflib-devel
setup      : |
    %configure --disable-static --disable-pyvips8
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check || :
