name       : libvips
version    : 8.8.1
release    : 17
source     :
    - https://github.com/libvips/libvips/releases/download/v8.8.1/vips-8.8.1.tar.gz : a0ee255a2a1ebfea5b2dff2a780824d7157a78c010d7ddd531279aacefbf2539
license    : LGPL-2.1-or-later
component  : multimedia.library
summary    : A fast image processing library with low memory needs
description: |
    libvips is a demand-driven, horizontally threaded image processing library. Compared to similar libraries, libvips runs quickly and uses little memory.
builddeps  :
    - pkgconfig(ImageMagick)
    - pkgconfig(OpenEXR)
    - pkgconfig(cfitsio)
    - pkgconfig(fftw3)
    - pkgconfig(gtk-doc)
    - pkgconfig(lcms2)
    - pkgconfig(libexif)
    - pkgconfig(libgsf-1)
    - pkgconfig(libpng)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(libturbojpeg)
    - pkgconfig(libtiff-4)
    - pkgconfig(libwebp)
    - pkgconfig(orc-0.4)
    - pkgconfig(pangoft2)
    - pkgconfig(poppler-glib)
    - pkgconfig(pygobject-3.0)
    - giflib-devel
setup      : |
    %configure --disable-static --disable-pyvips8
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check || :
